-- 2021년 5월 21일 
/*
함수(Function) : 기본적인 쿼리문을 강력하게 사용 
- 단일함수 : 각각의 행에 대해 실행, 각 row 하나당 하나의 결과 리턴
            select, where, order by
            문자열, 숫자, 날짜, 변환
- 그룹함수 : 집계를 할 수 있는 함수
            count, sum, avg...
*/

-- 문자열 함수
SELECT FIRST_NAME, LOWER(FIRST_NAME), UPPER(FIRST_NAME) FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) = 'KING';

-- 이름에 'S'가 들어가는 사람을 조회
SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%S%';

-- SUBSTR(문자열, 시작위치, N)
SELECT JOB_ID , SUBSTR(JOB_ID, 1, 2), SUBSTR(JOB_ID, 3,2), SUBSTR(JOB_ID, 4)
FROM EMPLOYEES;

-- INSTR() : JAVA의 charAt()
-- 'HELLO ORACLE!'

-- REPLACE(문자열, 찾는문자열, 바꿀문자열) :DUAL(DUMP TABLE명)
SELECT '010-1234-5678', REPLACE('010-1234-5678', '-', ' '), REPLACE('010-1234-5678', '-')
FROM DUAL;

-- 숫자함수 : ROUND(실수), CEIL(), FLOOR()
SELECT 1234.5678, ROUND(1234.5678), ROUND(1234.5678, 1), ROUND(1234.5678, -1)
FROM DUAL;

SELECT -1234.5678, ROUND(-1234.5678), ROUND(-1234.5678, 1), ROUND(-1234.5678, -1)
FROM DUAL;

-- ceil() 함수
SELECT 1234.5678, CEIL(1234.5678), CEIL(-1234.5678), FLOOR(1234.5678), FLOOR(-1234.5678)
FROM DUAL;

-- 날짜 데이터 다루기
SELECT SYSDATE AS 오늘, SYSDATE-1 AS 어제, SYSDATE+1 AS 내일
FROM DUAL;

SELECT SYSDATE - '91/12/25'
FROM DUAL; -- (X) 변환함수를 사용해야함

SELECT FIRST_NAME, ROUND(SYSDATE - HIRE_DATE) AS 근무일수
FROM EMPLOYEES;

SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3)
FROM DUAL;

-- MONTHS_BETWEEN(날짜,날짜)
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS 근무개월수
FROM EMPLOYEES;

-- MONTHS_BETWEEN(날짜,날짜) : 1년 12개월
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS 근무개월수
FROM EMPLOYEES;

-- 15년 이상(180개월 근무한 사람의 명단) -- 68명
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS 근무개월수
FROM EMPLOYEES
WHERE CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) >= 180
ORDER BY CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) DESC;

-- to_char, to_date
SELECT ceil(SYSDATE - to_date('91/12/25'))
FROM DUAL; -- 1991년 12월 25일생이 오늘까지 산 날짜

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM DUAL;

SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH:MI DAY') AS 현재
FROM DUAL;

-- EMPLOYEES 테이블에서 이름, 입사일(YYYY-MM-DD) 조건 2005년 이후에 입사한 사람들만 출력
SELECT FIRST_NAME, TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') AS 입사일
FROM EMPLOYEES
WHERE HIRE_DATE >= '05/01/01';

-- 기타함수(DECODE : IF문) - 10->10%, 20->5% 30->3%
SELECT DISTINCT DEPARTMENT_ID 
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

-- 기타함수(DECODE : IF문) - 10->10%, 20->5% 30->3%
SELECT FIRST_NAME, DEPARTMENT_ID, SALARY,
    DECODE(DEPARTMENT_ID, 
            10, SALARY * 1.1, 
            20, SALARY * 1.05, 
            30, SALARY * 1.03,
            SALARY) AS 인상급여
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;









