
--1
SELECT
    FIRST_NAME, SUBSTR(PHONE_NUMBER, 1, 3)
FROM
    EMPLOYEES;
    
--2    
SELECT
    FIRST_NAME, LAST_NAME, LENGTH(FIRST_NAME)+LENGTH(LAST_NAME) AS 이름글자수
FROM
    EMPLOYEES;
    
SELECT
    FIRST_NAME, LAST_NAME, LENGTH(FIRST_NAME || LAST_NAME) AS이름글자수
FROM
    EMPLOYEES;


--3
SELECT
    FIRST_NAME, LAST_NAME, SUBSTR(first_name, 0, 1) ||','||SUBSTR(last_name, 0, 1) AS 첫글자
    
FROM
    EMPLOYEES;
    
--4    
SELECT * FROM EMPLOYEES
WHERE UPPER(JOB_ID) LIKE 'SA%';

--5
SELECT
    UPPER(FIRST_NAME)FIRST_NAME, UPPER(LAST_NAME)LAST_NAME
FROM 
    EMPLOYEES;
--6    
SELECT 
    FIRST_NAME, LAST_NAME, REPLACE(PHONE_NUMBER, '.','-') AS PHONENO
FROM 
    EMPLOYEES;


--7
SELECT
    FIRST_NAME, SALARY, ROUND(SALARY / 30, 1) AS 일일급여
FROM 
    EMPLOYEES;
    
--8    
SELECT
    DEPARTMENT_ID, HIRE_DATE, HIRE_DATE + 100 AS 근무100일째날
FROM 
    EMPLOYEES;
    
--9
SELECT
    FIRST_NAME, DEPARTMENT_ID, HIRE_DATE, CEIL(SYSDATE - HIRE_DATE) AS근무일수
FROM 
    EMPLOYEES
ORDER BY HIRE_DATE DESC;


--10
SELECT
    DEPARTMENT_ID, HIRE_DATE, FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS 근속개월수
FROM 
    EMPLOYEES;
    
    
--11    
SELECT
    FIRST_NAME, DEPARTMENT_ID, TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일" DAY')  AS 입사일
FROM 
    EMPLOYEES;

--12
SELECT
    FIRST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM
    EMPLOYEES
WHERE
    HIRE_DATE LIKE '__/03/__'
ORDER BY HIRE_DATE    ;
    
--13    
SELECT
    TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS')
FROM
    DUAL;


--14    
SELECT
    FIRST_NAME, 
    DECODE( DEPARTMENT_ID,
            40, '인사',
            60, '전산',
            80, '영업',
            '기타')
FROM EMPLOYEES;